[project]
name = "timetrack"
version = "0.2.0"
description = "Easy timetracking in Berlin from command line"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "workalendar",
]

[tool.uv.sources]
workalendar = { git = "ssh://git@github.com/sgoth/workalendar" }

[tool.setuptools]
py-modules = ["timetrack"]

[tool.setuptools.packages.find]
where = ["."]
include = ["tt*"]

[project.scripts]
tt = "tt.timetrack:main"